version: '3.7'

services:
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:latest
    restart: unless-stopped
    ports:
      - 8002:80
      - 3012:3012
    environment:
      - TZ=$TZ
      - PUID=$PUID
      - PGID=$PGID
      - WEBSOCKET_ENABLED=true
      - DOMAIN=$DOMAIN
      - LOGIN_RATELIMIT_MAX_BURST=10
      - LOGIN_RATELIMIT_SECONDS=60
      - ADMIN_RATELIMIT_MAX_BURST=10
      - ADMIN_RATELIMIT_SECONDS=60
      - SENDS_ALLOWED=false
      - EMERGENCY_ACCESS_ALLOWED=true
      - WEB_VAULT_ENABLED=true
      - ADMIN_TOKEN=$ADMIN_TOKEN
      - INVITATIONS_ALLOWED=true
      - SHOW_PASSWORD_HINT=false
      - SIGNUPS_ALLOWED=true
    volumes:
      - vaultwarden:/data
    networks:
      vaultwarden:

networks:
  vaultwarden:
    name: vaultwarden
    driver: bridge

volumes:
  vaultwarden:
    name: vaultwarden
