version: "3.7"

services:
  linkwarden:
    image: ghcr.io/linkwarden/linkwarden:v2.4.9
    container_name: linkwarden
    environment:
      - DATABASE_URL=postgresql://tipi:${LINKWARDEN_DB_PASSWORD}@linkwarden-db:5432/linkwarden
      - NEXTAUTH_SECRET=${LINKWARDEN_NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${APP_PROTOCOL:-http}://${APP_DOMAIN}/api/v1/auth
      - NEXT_PUBLIC_DISABLE_REGISTRATION=${LINKWARDEN_NEXT_PUBLIC_DISABLE_REGISTRATION}
    restart: unless-stopped
    volumes:
      - ${DATA_DIR}/linkwarden:/data/data
    ports:
      - 3000:3000
    depends_on:
      - linkwarden-postgres
    networks:
      - pegasus

  linkwarden-postgres:
    container_name: linkwarden-postgres
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=tipi
      - POSTGRES_PASSWORD=${LINKWARDEN_DB_PASSWORD}
      - POSTGRES_DB=linkwarden
    volumes:
      - ${DATA_DIR}/linkwarden-postgres:/var/lib/postgresql/data
    networks:
      - pegasus

volumes:
  linkwarden:
    name: linkwarden

networks:
  pegasus:
    external: true
