version: "3.7"

services:
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:0.15.3
    restart: unless-stopped
    volumes:
      - ${DATA_DIR}/homarr/config:/app/data/configs
      - ${DATA_DIR}/homarr/icons:/app/public/icons
      - ${DATA_DIR}/homarr/dashboard:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PASSWORD=${PASSWORD}
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    ports:
      - 7575:7575
    networks: 
      - pegasus

volumes:
  homarr:
    name: homarr
    driver: local

networks:
  pegasus:
    external: true
