version: "3.7"

services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: always
    ports:
      - 9000:9000
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    environment:
      - TZ=America/Sao_Paulo
      - PUID=1000
      - PGID=1000
    network_mode: 'bridge'

volumes:
  portainer-data:
