version: '3.7'

volumes:
  bitwarden:
  bitwarden-postgres:


networks:
  bitwarden:
    name: bitwarden
    driver: bridge
    enable_ipv6: false
    ipam:
      config:
        - subnet: ${BITWARDEN_SUBNET}

services:
  bitwarden:
    container_name: bitwarden
    image: vaultwarden/server:latest
    restart: unless-stopped
    ports:
      - 8002:80
      - 3012:3012
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - WEBSOCKET_ENABLED=true
      - DOMAIN=${DOMAIN}
      - LOGIN_RATELIMIT_MAX_BURST=10
      - LOGIN_RATELIMIT_SECONDS=60
      - ADMIN_RATELIMIT_MAX_BURST=10
      - ADMIN_RATELIMIT_SECONDS=60
      - SENDS_ALLOWED=false
      - EMERGENCY_ACCESS_ALLOWED=true
      - WEB_VAULT_ENABLED=true
      - ADMIN_TOKEN=${ADMIN_TOKEN}
      - INVITATIONS_ALLOWED=true
      - SHOW_PASSWORD_HINT=true
      - SIGNUPS_ALLOWED=false
    volumes:
      - bitwarden:/data
      - bitwarden:/log
    networks:
      bitwarden:
        ipv4_address: ${BITWARDEN_IPV4_ADDRESS}
    depends_on:
      - bitwarden-postgres

  bitwarden-postgres:
    container_name: bitwarden-postgres
    restart: always
    image: postgres:alpine
    ports:
      - 5433:5432
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - bitwarden-postgres:/var/lib/postgresql/data
    networks:
      bitwarden:
        ipv4_address: ${POSTGRES_IPV4_ADDRESS}
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}'
        ]
      interval: 5s
      timeout: 5s
      retries: 10
