- Group A:
    - Sonarr:
        icon: sonarr.png
        href: http://sonarr.host/
        description: Series management

- Group B:
    - Radarr:
        icon: radarr.png
        href: http://radarr.host/
        description: Movie management
        siteMonitor: http://sonarr.host/

- Group C:
    - Service:
        icon: mdi-flask-outline
        href: http://service.host/
        description: My cool service
        ping: some.other.host

- Docker:
    - Portainer:
        href: http://localhost/
        description: This is another service
        server: other-server
        container: other-container

- Media:
    - Plex:
        id: 100
        icon: plex.png
        href:
        container: plex
        widget:
          type: plex
          fields: ["streams", "movies", "tv"]
          url:
          key: #plex-token
