version: '3.7'

services:
  wireguard:
    container_name: wireguard
    image: lscr.io/linuxserver/wireguard:latest
    restart: always
    ports:
      - 51820:51820/udp
    cap_add:
      - NET_ADMIN
      - SYS_MODULE 
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - SERVERURL=auto
      - SERVERPORT=51820 
      - PEERS=10
      - PEERDNS=auto 
      - INTERNAL_SUBNET=10.0.0.0
      - ALLOWEDIPS=0.0.0.0/0 
      - LOG_CONFS=true 
    volumes:
      - wireguard:/config
      - /usr/src:/usr/src # location of kernel headers
      - /lib/modules:/lib/modules 
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
volumes:
  wireguard:
    name: wireguard
