version: '3.8'

volumes:
  postgres:
  n8n:


networks:
  n8n:
    name: n8n
    driver: bridge
    enable_ipv6: false
    ipam:
      config:
        - subnet: ${SUBNET}

services:
  n8n-postgres:
    container_name: n8n-postgres
    restart: always
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - n8n
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}'
        ]
      interval: 5s
      timeout: 5s
      retries: 10

  n8n:
    container_name: n8n
    restart: always
    image: docker.n8n.io/n8nio/n8n
    ports:
      - 5678:5678
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - DB_POSTGRESDB_HOST=postgres
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - N8N_HOST=${SUBDOMAIN}.${DOMAIN}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_URL=https://${SUBDOMAIN}.${DOMAIN}/
    volumes:
      - n8n:/home/node/.n8n
      - n8n:/files
    networks:
      n8n:
        ipv4_address: ${IPV4_ADDRESS}
    command: /bin/sh -c "n8n start --tunnel"
    depends_on:
      n8n-postgres:
        condition: service_healthy
