version: "3.7"

services:
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:0.14.4
    restart: unless-stopped
    volumes:
      - /homarr/config:/app/data/configs
      - /homarr/icons:/app/public/icons
      - /homarr/dashboard:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PASSWORD=${PASSWORD}
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    ports:
      - 7575:7575
    networks: 
      - homarr

networks:
  homarr:
    name: homarr
    driver: bridge

volumes:
  homarr:
    name: homarr
    driver: local


