version: "3.9"

services:
  firefly:
    image: fireflyiii/core:version-6
    container_name: firefly
    restart: unless-stopped
    volumes:
      - ${DATA_DIR}/firefly/upload:/var/www/html/storage/upload
    ports:
      - 8081:8080
    depends_on:
      - firefly-mysql
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      
      # Firefly
      - APP_ENV=${APP_ENV}
      - APP_DEBUG=${APP_DEBUG}
      - SITE_OWNER=${SITE_OWNER}
      - APP_KEY=${APP_KEY}
      - STATIC_CRON_TOKEN=${STATIC_CRON_TOKEN}
      - TRUSTED_PROXIES=${TRUSTED_PROXIES}
      - APP_NAME=${APP_NAME}
      - BROADCAST_DRIVER=${BROADCAST_DRIVER}
      - QUEUE_DRIVER=${QUEUE_DRIVER}
      - CACHE_PREFIX=${CACHE_PREFIX}
      - IS_HEROKU=${IS_HEROKU}
      - FIREFLY_III_LAYOUT=${FIREFLY_III_LAYOUT}
      - APP_URL=${APP_URL}
      - ALLOW_WEBHOOKS=${ALLOW_WEBHOOKS}

      # Database
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${MYSQL_HOST}
      - DB_PORT=${MYSQL_PORT}
      - DB_DATABASE=${MYSQL_DATABASE}
      - DB_USERNAME=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}

      # Cookie settings
      - COOKIE_PATH=${COOKIE_PATH}
      - COOKIE_DOMAIN=${COOKIE_DOMAIN}
      - COOKIE_SECURE=${COOKIE_SECURE}
      - COOKIE_SAMESITE=${COOKIE_SAMESITE}
    networks:
      - pegasus

  firefly-mysql:
    container_name: firefly-mysql
    image: mariadb
    hostname: firefly-mysql
    restart: unless-stopped
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=${MYSQL_RANDOM_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ${DATA_DIR}/firefly-mysql/db:/var/lib/mysql
    networks:
      - pegasus

  firefly-cron:
    container_name: firefly-cron
    restart: unless-stopped
    image: alpine
    command: 
      sh -c "echo \"${CRON} wget -qO- ${APP_URL}/api/v1/cron/${STATIC_CRON_TOKEN}\" | crontab - && crond -f -L /dev/stdout"
    networks:
      - pegasus

volumes:
  firefly-mysql:
    name: firefly-mysql
  firefly:
    name: firefly

networks:
  pegasus:
    external: true
