version: '3.3'

services:
  healthchecks:
    image: lscr.io/linuxserver/healthchecks:latest
    container_name: healthchecks
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - SITE_ROOT=${SITE_ROOT}
      - SITE_NAME=${SITE_NAME}
      - DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - EMAIL_USE_TLS=${EMAIL_USE_TLS}
      - SUPERUSER_EMAIL=${SUPERUSER_EMAIL}
      - SUPERUSER_PASSWORD=${SUPERUSER_PASSWORD}
      - REGENERATE_SETTINGS=
      - ALLOWED_HOSTS=
      - APPRISE_ENABLED=
      - DEBUG=
      - INTEGRATIONS_ALLOW_PRIVATE_IPS=
      - PING_EMAIL_DOMAIN=
      - SECRET_KEY=
      - SITE_LOGO_URL=
    volumes:
      - /path/to/healthchecks/config:/config
    ports:
      - 8000:8000
      - 2525:2525
    restart: unless-stopped
