version: '3.7'

services:
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:latest
    restart: unless-stopped
    ports:
      - 8002:80
      - 3012:3012
    volumes:
      - bw-data:/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - bw-data:/log
    environment:
      - WEBSOCKET_ENABLED=true
      - SIGNUPS_ALLOWED=true
      - ADMIN_TOKEN=<ADMIN_PW>
      - INVITATIONS_ALLOWED=true
      - SHOW_PASSWORD_HINT=false

volumes:
  vaultwarden:


