networks:
  uptime-kuma:
    external: true

volumes:
  uptime-kuma:
    name: uptime-kuma

services:
  uptime-kuma:
    image: louislam/uptime-kuma
    container_name: uptime-kuma
    restart: unless-stopped
    ports:
      - 3001:3001
    environment:
      - TZ=$TZ
    volumes:
      - ${DATA_DIR}:/app/data
    security_opt:
      - no-new-privileges:true
    networks:
      - uptime-kuma

  uptime-kuma-docker-proxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    container_name: uptime-kuma-docker-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    healthcheck:
      test: wget --spider http://localhost:2375/version || exit 1
      interval: "29s"
      timeout: "5s"
      retries: 3
      start_period: "21s"
    environment:
      - CONTAINERS=1
      - POST=0
    networks:
      - uptime-kuma

