version: '3.7'

services:
  uptime-kuma:
    image: louislam/uptime-kuma
    container_name: uptime-kuma
    restart: unless-stopped
    ports:
      - 3001:3001
    environment:
      - TZ=$TZ
      - PUID=$PUID
      - PGID=$PGID
    volumes:
      - ${DATA_DIR}/uptime-kuma:/app/data
    security_opt:
      - no-new-privileges:true
    networks:
      - pegasus

  docker-proxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    container_name: docker-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    healthcheck:
      test: wget --spider http://localhost:2375/version || exit 1
      interval: "29s"
      timeout: "5s"
      retries: 3
      start_period: "21s"
    environment:
      - CONTAINERS=1
      - POST=0
    networks:
      - pegasus

networks:
  pegasus:
    external: true

volumes:
  uptime-kuma:
    name: uptime-kuma
