version: "3"

services:
  doku:
    container_name: doku
    restart: 'always'
    image: amerkurev/doku:v0.0.16
    ports:
      - 9090:9090
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/hostroot:ro
    networks:
      - pegasus

networks:
  pegasus:
    external: true
