version: "3.8"

services:
  dockge:
    image: louislam/dockge:1.4.2
    container_name: dockge
    restart: unless-stopped
    ports:
      - 5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DATA_DIR}/dockge:/app/data
      - ${DATA_DIR}/dockge/stacks:${DATA_DIR}/dockge/stacks
    environment:
      # Tell Dockge where is your stacks directory
      - DOCKGE_STACKS_DIR=${DATA_DIR}/dockge/stacks
    networks:
      - pegasus

volumes:
  dockge:
    name: dockge

networks:
  pegasus:
    external: true
