version: "3.8"

services:
  duplicati:
    container_name: duplicati
    restart: unless-stopped
    image: lscr.io/linuxserver/duplicati:latest
    ports:
      - 8200:8200
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /duplicati/config:/config
      - /:/source
      - /var/backups:/backups
    networks:
      - duplicati

volumes:
  duplicati:
    driver: local
    driver_opts:
      type: none
      device: /opt/duplicati
      o: bind

networks:
  duplicati:
    name: duplicati
    driver: bridge
    enable_ipv6: false
    ipam:
      config:
        - subnet: "172.18.0.0/16"
